### ISSUE TITLE
How about the predict results?

### ISSUE THREAD

**Issue by l35633** [erkil1452/gaze360#10]
hello, dear friend!
I wonder the prediction result is (Yaw, Pitch, Roll)?
and how to change to Two dimensional coordinates？
Thanks  a lot!

**Comment by erkil1452** [comment]
The output in angular_output (https://github.com/erkil1452/gaze360/blob/master/code/model.py, L51) is Yaw and Pitch in radians. That is [0,0] marks the person looks straight into the camera.
