### ISSUE TITLE
Static model

### ISSUE THREAD

**Issue by KORIYN** [erkil1452/gaze360#13]
Hello  Petr Kellnhofer,

I am a student in Xidian University, in China, and I am learning gaze estimation. After reading your paper accepted by ICCV2019, I have learned so much. But I can only find the LSTM model on your Github link, and I need to test the static model. Could you provide the static model for me?
 
I will be very appreciate if you could send the static mode of " Gaze360: Physically Unconstrained Gaze Estimation in the Wild "in ICCV2019 for me. 

Thanks very much! Best wishes for you!

Gerong

**Comment by Hopedreams** [comment]
Hello，I am a student ，too.Can you add a contact number?

**Comment by PrimeshShamilka** [comment]
This repo provides a good implementation of the static model. 
https://github.com/yihuacheng/Gaze360
