### ISSUE TITLE
Python 2 is deprecated in Colab.

### ISSUE THREAD

**Issue by ruofei7** [erkil1452/gaze360#17]
@erkil1452  Python2 has been deprecated by Colab, so the demo code cannot be run on Google Colab notebook. Is there any other way to deal with it?

**Comment by erkil1452** [comment]
I am not really familiar with Colab (the demo was done by my co-author) but the original code runs in python3. Hence, I imagine it cannot be very hard to modify the Colab code to run in python3 as well. In the worst case, you should be able to copy out the scripts and just run it locally.
