### ISSUE TITLE
Prediction for single image

### ISSUE THREAD

**Issue by hek14** [erkil1452/gaze360#2]
Thanks for sharing the code for gaze360. As far as I know, the model is trained on 7-frame videos, what changes should I make to use the model for predicting gaze vector for single image?

**Comment by italojs** [comment]
I guess it' not possible because it uses [LSTM](https://en.wikipedia.org/wiki/Long_short-term_memory), this deep learning architecture don't allow you to use one single image, you need an image sequence

**Comment by ashesh-0** [comment]
For cross-dataset evaluation, they have not used LSTM but have gone with a very simple architecture consisting of a pretrained ResNet-18 with two final layers to compute the prediction.

**Comment by arduinepo** [comment]
@hek14 : Just feed the model with the image as argument : self.model(image)

**Comment by erkil1452** [comment]
Correct, just skip the LSTM layer and use only single input branch.

**Comment by nhathoang0110** [comment]
Hello. Has anyone successfully implemented on an image, can you give me the source code? I tried to edit it but it doesn't work

**Comment by VeruGromnicova** [comment]
Hello, I have the same problem, I did not find out how to skip the LSTM and apply code to one image only. I tried edit the code but it doesn't work for me neither. Does anyone have any clue? Thanks.

**Comment by horanyinora** [comment]
Hello,
Anyone solved this? Thanks

**Comment by ashesh-0** [comment]
You can use this as the model.  This gives me expected results. 

```
import math

import torch.nn as nn

from resnet import resnet18


class GazeStaticModel(nn.Module):
    def __init__(self, output_dim=3):
        super(GazeStaticModel, self).__init__()
        self.img_feature_dim = 256  # the dimension of the CNN feature to represent each frame
        self.output_dim = output_dim
        self.base_model = resnet18(pretrained=True)

        # The linear layer that maps the LSTM with the 3 or 2 outputs
        self.last_layer = nn.Linear(self.img_feature_dim, output_dim)

    def forward(self, input):
        base_out = nn.ReLU()(self.base_model(input))
        output = self.last_layer(base_out).view(-1, self.output_dim)

        angular_output = output[:, :2]
        # YAW
        angular_output[:, 0:1] = math.pi * nn.Tanh()(angular_output[:, 0:1])
        # Pitch
        angular_output[:, 1:2] = (math.pi / 2) * nn.Tanh()(angular_output[:, 1:2])
        if self.output_dim == 2:
            return angular_output
        assert self.output_dim == 3
        var = math.pi * nn.Sigmoid()(output[:, 2:3])
        var = var.view(-1, 1).expand(var.size(0), 2)

        return angular_output, var
```

**Comment by horanyinora** [comment]
Hello,

Thanks for the reply. Which checkpoint are you using with this model? Did you train the static model or are the weights available somewhere for the static model?
If I use the checkpoint provided by the authors I get the following message:

> RuntimeError: Error(s) in loading state_dict for DataParallel:
> 	Unexpected key(s) in state_dict: "module.lstm.bias_hh_l1", "module.lstm.bias_hh_l0", "module.lstm.bias_ih_l1_reverse", "module.lstm.weight_hh_l0_reverse", "module.lstm.bias_hh_l1_reverse", "module.lstm.bias_ih_l0_reverse", "module.lstm.weight_ih_l0", "module.lstm.bias_ih_l1", "module.lstm.weight_ih_l1_reverse", "module.lstm.weight_hh_l1", "module.lstm.weight_ih_l1", "module.lstm.weight_ih_l0_reverse", "module.lstm.weight_hh_l0", "module.lstm.weight_hh_l1_reverse", "module.lstm.bias_ih_l0", "module.lstm.bias_hh_l0_reverse". 
> 	size mismatch for module.base_model.fc2.bias: copying a param of torch.Size([3]) from checkpoint, where the shape is torch.Size([256]) in current model.
> 	size mismatch for module.base_model.fc2.weight: copying a param of torch.Size([3, 1000]) from checkpoint, where the shape is torch.Size([256, 1000]) in current model.
> 	size mismatch for module.last_layer.weight: copying a param of torch.Size([3, 256]) from checkpoint, where the shape is torch.Size([3, 512]) in current model.

After running the code with the static model without loading the checkpoint I got the following error:
`RuntimeError: Given groups=1, weight of size [64, 3, 7, 7], expected input[1, 21, 224, 224] to have 3 channels, but got 21 channels instead`

Many thanks!

**Comment by ashesh-0** [comment]
Hmm, so this is not a cooked food. It is one ingredient of the recipe ;) 
There is no checkpoint to load from for this model. You will have to train it. For training it, you cannot use the data loader given here for lstm model.  It is so bcoz that returns 7 images and for this you need just one image. 

If you don't want to do all that effort, then you may just use the lstm model. You just have to change data loader. There you will have to return 7 copies of the same image. In this way you can use the checkpoint as well.
