### ISSUE TITLE
fail to obtain gaze360 dataset

### ISSUE THREAD

**Issue by Angel113110** [erkil1452/gaze360#20]
Hi, I have registered successfully yesterday. But, I can't login for dataset until now. How long should I wait for? Several hours seems not true. Is there any other ways for dataset? 

Looking forward to your reply.

Thanks!

**Comment by 0tanjie0** [comment]
Hello， I got the same problem as yours. Have you finished？

**Comment by BigBookPlus** [comment]
me too, any solutions?

**Comment by BigBookPlus** [comment]
I can download now. it seems that we need to wait a little while.

**Comment by Angel113110** [comment]
@xvling Can you download the whole dataset and share it to me through baiduyun or other device like baiduyun ? I still can't download it. Looking forwrad your reply.

**Comment by tianjun-world** [comment]
> I can download now. it seems that we need to wait a little while.

Can you download the whole dataset and share it to me through baiduyun or other device like baiduyun ? I still can't download it. Looking forwrad your reply.

**Comment by leemengxing** [comment]
@erkil1452 @Angel113110 @xvling I want to get the gaze360 data set, but it prompts 403 access forbidden. How to register for permission, thanks for answering the question.

**Comment by erkil1452** [comment]
You likely got IP blocked after too many log in attempts. Please send us your IP by e-mail.

**Comment by Angel113110** [comment]
@erkil1452 My IP is 10.31.12.74.

**Comment by erkil1452** [comment]
That is your private IP address. You need the public one: https://www.google.com/search?&gl=us&q=what+is+my+ip+address

**Comment by leemengxing** [comment]
hello，my ip is 161.81.91.191. thks@erkil1452

**Comment by erkil1452** [comment]
This IP is not and was not blocked.

**Comment by erkil1452** [comment]
@leemengxing I've reset the counter but it was not actually blocked.

**Comment by Angel113110** [comment]
@erkil1452 , my ip is 42.3.27.252

**Comment by erkil1452** [comment]
Your IP is not blocked.

**Comment by vikrant7** [comment]
@erkil1452 I am not able to register. My domain is jp.honda. Please help.
