### ISSUE TITLE
where is the physical location of the origin of Ladybug camera coordinate system?

### ISSUE THREAD

**Issue by taoye0606** [erkil1452/gaze360#21]
as mentioned in the ICCV2019 paper 'The  Ladybug5  consists  of  five  synchronized and overlapping 5 megapixel camera' and the metadata also provides the 'index of the camera'. it seems that the subject and the target are captured by different cameras. Generally each camera has its own coordinate, so which camera dose 'the Ladybug camera coordinate system' based on?

**Comment by erkil1452** [comment]
It is based on a point somewhere in the middle of all the cameras. The Ladybug sdk handles the conversions between this coordinate system and the local camera coordinate systems (there is one for each camera) so all the provided 3D locations are valid with respect to this central neutral origin.
