### ISSUE TITLE
Colab notebook error Lucid

### ISSUE THREAD

**Issue by gv237-07** [erkil1452/gaze360#22]
Has anyone tried running the Colab Notebook please? I'm getting an error `ModuleNotFoundError: No module named 'lucid'` when trying to run `import lucid.misc.io.showing as show`. Thank you for your help

**Comment by LinReseach** [comment]
Yes,I recently encounter the problem.and I am very troubled for that. Have you solved this?

**Comment by erkil1452** [comment]
Hi, the old version is not working anymore due to some dependencies.

Here is an updated colab: https://colab.research.google.com/drive/1SJbzd-gFTbiYjfZynIfrG044fWi6svbV?usp=sharing

There is still an issue with the lucid import in cell #28. It fails the first time it is called but if you rerun the cell it works fine.

**Comment by LinReseach** [comment]
Hi,Petr

Thanks for your reply,I tried the demo,and it works well.It is very helpful
for my project and benefits me a lot.I am very appreciate for you.

Best Regards
Lin

Petr Kellnhofer ***@***.***> 于2022年1月27日周四 19:10写道：

**Comment by LinReseach** [comment]
> Hi, the old version is not working anymore due to some dependencies.
> 
> Here is an updated colab: https://colab.research.google.com/drive/1SJbzd-gFTbiYjfZynIfrG044fWi6svbV?usp=sharing
> 
> There is still an issue with the lucid import in cell #28. It fails the first time it is called but if you rerun the cell it works fine.
Thank you very much! I tried it and it works well!

**Comment by LinReseach** [comment]
Thank you very much,I tried the demo,and it works well.

**Comment by LinReseach** [comment]
Thank you very much,I tried the new demo,and it works well.

**Comment by JohnPravin97** [comment]
I am trying to use the Notebook V2 and I am getting an error with "import lucid.misc.io.showing as show". 
I have the estimated 3d gaze values from a image and my aim is to visualize using the lucid and opengl for an image but could not able to achieve it. Can anybody help me? 
Can I get a code which takes the 3d gaze values and the image and plots the gaze arrow onto the image?
