### ISSUE TITLE
Dataset access

### ISSUE THREAD

**Issue by horanyinora** [erkil1452/gaze360#23]
I tried to follow the link (http://gaze360.csail.mit.edu/). I got the following error message using different browsers and devices:

Forbidden
You don't have permission to access / on this server.
Apache/2.4.7 (Ubuntu) Server at gaze360.csail.mit.edu Port 80

Could you please check this issue?
Thanks!

**Comment by leemengxing** [comment]
I also encountered this problem，Thanks !

**Comment by horanyinora** [comment]
I was able to download the dataset successfully.

**Comment by leemengxing** [comment]
me too.  thanks!

**Comment by Angel113110** [comment]
@leemengxing @horanyinora  Can you share dataset with me ? I can't login for the time being.
