### ISSUE TITLE
Unable to login the account for the Gaze360

### ISSUE THREAD

**Issue by Haiyuan-Liu** [erkil1452/gaze360#27]
To whom it may concern,

I was trying to register for the account to access the Gaze360 dataset for a human interaction project.

It seems I can not log in with the activated e-mail address. There might be some problems with the dataset login system. I could not log in with the right password. I tried few times and got forbidden. And I could not contact you via the email address <pkellnho@mit.edu>. And I have sent the email to <opengaze.online@gmail.com>. Could you please help me? 

Best regards,
Haiyuan Liu

**Comment by Haiyuan-Liu** [comment]
It works now. Thanks!

**Comment by biyoml** [comment]
I cannot, either. How did you solve it?
