### ISSUE TITLE
test error

### ISSUE THREAD

**Issue by Hopedreams** [erkil1452/gaze360#28]
Using the author's code,the mean angle error of the model is 12.8 degrees.There is a certain gap with the results in the essay.What could be the reason?

**Comment by RSKothari** [comment]
You are most likely reporting the validation result.

**Comment by Hopedreams** [comment]
![image](https://user-images.githubusercontent.com/81133186/123531715-7d495e00-d739-11eb-9fa1-d0fbf156c3b8.png)
Results in the essay is 11.4 degree.  How can I solve this problem?

**Comment by RSKothari** [comment]
Could you clarify which result you are referring to? Are you trying to
reproduce the frontal results?

The code is designed to reproduces 13.5 degrees ( all 360 degree )

**Comment by Hopedreams** [comment]
The test error is 12.8 degree.
No, I want to repoduce all 360 degree.
Thanks a lot. I was mistaken in thinking.

**Comment by RSKothari** [comment]
Hmm .. I have reproduced the authors code many times and I can confirm that I can reproduce 13.5.
I recommend first downloading the weights provided by the authors and confirm if you can reproduce 13.5. If not, then it indicates some data files might be missing.

**Comment by Hopedreams** [comment]
Thank you very much.Inspired by you,I reconfirmed and the result is 13.5.

**Comment by Hopedreams** [comment]
![image](https://user-images.githubusercontent.com/81133186/131843171-0443e757-ef98-4d1a-9f7c-748c5d0dccdd.png)
Why are pitch and yaw defined in this way?

**Comment by erkil1452** [comment]
The tanh should not be interpreted geometrically. It is a common nonlinearity used in machine learning and we use it to squeeze the output to the range (-1,1). This is then easy to rescale to the range required for yaw (-pi, pi) and pitch (-pi/2, pi/2) angles as seen above.

**Comment by Hopedreams** [comment]
Is the output of the model a three-dimensional vector?





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "erkil1452/gaze360"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年10月2日(星期六) 凌晨2:39
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [erkil1452/gaze360] test error (#28)





 
The tanh should not be interpreted geometrically. It is a common nonlinearity used in machine learning and we use it to squeeze the output to the range (-1,1). This is then easy to rescale to the range required for yaw (-pi, pi) and pitch (-pi/2, pi/2) angles as seen above.
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by erkil1452** [comment]
The output is yaw and pitch in polar coordinates which can be converted into 3D direction using
```
x = sin(yaw) * cos(pitch)
y = sin(pitch)
z = cos(yaw) * cos(pitch)
```

**Comment by Hopedreams** [comment]
Does this 3D direction refer to the coordinates (x, y, z) of the vector in the Cartesian coordinate system?

**Comment by erkil1452** [comment]
Yes, it is a 3D direction in the Cartesian coordinate system of the camera.

**Comment by Hopedreams** [comment]
What do these three output values represent respectively? Thank you very much


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "erkil1452/gaze360"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年11月3日(星期三) 晚上10:32
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [erkil1452/gaze360] test error (#28)





 
Yes, it is a 3D direction in the Cartesian coordinate system of the camera.
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by erkil1452** [comment]
The gaze vector components (x, y and z).
