### ISSUE TITLE
about the data normalization

### ISSUE THREAD

**Issue by haijing1995** [erkil1452/gaze360#31]
Hi, thanks for your great work, I have some questions about inference on my own data.
Like _Revisiting data normalization for appearance-based gaze estimation
and Learning-by-synthesis for appearance-based 3d gaze estimation_ ,  the face image need to be normalized using some  matrix, but you mentioned in  #30 that you do not do any face normalization.
So when I test a new image on a model trained on the face images in Gaze360, I just need to crop the face using the bounding box and feed it into the model?

**Comment by erkil1452** [comment]
That is correct. We rely on the CNN to figure out the normalization.
