### ISSUE TITLE
how to get train.txt

### ISSUE THREAD

**Issue by jxncyym** [erkil1452/gaze360#32]
@erkil1452  how can i get the train.txt, val.txt, and test.txt？ coulde you provide me the code?
thanks !!

**Comment by erkil1452** [comment]
Hi, the files you are asking for are right here in the git: https://github.com/erkil1452/gaze360/tree/master/code

You can also create them yourself using the the split flag in the metadata.mat as described here:
https://github.com/erkil1452/gaze360/blob/master/dataset/README.md
