### ISSUE TITLE
An error occurred in the test results

### ISSUE THREAD

**Issue by liyixin-1** [erkil1452/gaze360#45]
@erkil1452 hello！I'm sorry to bother you, I'm having some problems while running the code. My test had an angular error of 75, and my attempt to modify some parameters didn't help. Can you tell me some possible reasons? Thank you ！
![微信图片_20220524224804](https://user-images.githubusercontent.com/54573007/170140578-bd6ae844-15c8-432f-9118-e0ebb7dcf198.png)

**Comment by erkil1452** [comment]
The error is very large, almost the same as an error between two random vectors. Most likely either your predicted gaze or the gt labels are mismatched.
