### ISSUE TITLE
How to get mean angular errors

### ISSUE THREAD

**Issue by LinReseach** [erkil1452/gaze360#48]
Hi,Petr.Thanks for your work.I have a question to your paper 'Gaze360: Physically Unconstrained Gaze Estimation in the Wild'.In table2 you reports the mean angular errors for various models.How you get this mean angular error? (yaw error+pitch error)/2?

**Comment by erkil1452** [comment]
Hi, we convert both gaze vectors (prediction and GT) into cartesian coordinate system `g=(x,y,z)`, normalize their lengths and the compute the angle between them as `error=arccos(dot(g1,g2))`
