### ISSUE TITLE
Adapting to detectron2 : wrong predicted multiple heads boxes

### ISSUE THREAD

**Issue by arduinepo** [erkil1452/gaze360#5]
Hi,

I [adapted](https://github.com/arduinepo/gaze360-Adapter) the Colab tutorial to detectron2, and rewrote the script into three classes to make it clearer. It works well on single people pictures ; but not at all on multiple people pictures, for example : 
![test30](https://user-images.githubusercontent.com/33550367/75254864-4e3b7900-57e1-11ea-8a47-c1e9504e33ce.jpg)
Could anyone please help me ? I thank you a lot.

**Comment by carlosimoes** [comment]
@arduinepo 
I'm interested in what you're doing and if you want i can try to help in this project.
I'm going to analyze the code and then i will say something. 
[Just to keep the topic alive and you know that i will take a look]

But at first glance have you already confirmed whether each person's head is being well analyzed in each frame (the masks).  Because the gaze360 needs a crop image of the head individually to get the gaze vector.

**Comment by arduinepo** [comment]
Hi,
thank you for your answer !
In fact I succeeded a few hours after posting this issue, quite easily by modifying some lines in the function extracts_heads__bbox : since detectron2 returns the cropped IUV image for each instance, the individual segmentation masks are not needed to obtain the individual heads. My code is on my office computer to which I usually connect via x2go and SSH, but my laptop has got a permission denied since this morning, so I will only commit on Monday morning. ;-)
I'm now working on accelerating the program : after a timed run, with a GPU and a batched inputs for the DensePOse predictor, the slowest part is the extraction of the densepose results, the IUV arrays and the boxes ; I haven't yet feeded the gaze predictor with multiple inputs, nor timed the transformation of the extracted data before getting the gaze. I am going to explore DALI and multiprocessing, because I plan on retraining gaze360 with exact groundtruth values (usings markers in a lab room, maybe 2+ cameras) : the outputs don't satisfy me.

**Comment by carlosimoes** [comment]
Hi @arduinepo 

Thank you for your answer and i would be very grateful if you commit the corrections.

I was thinking of using gaze360 on a project for the university but had problems with the installation of detectron so a change to detectron2 and had problems with the outputs of the gaze360, as you could imagine. If you permit me I would use the code you made to my project.

The project consists basically of Gaze Detection and the visual focus of attention for Human-Robot Interaction Engagement.

This is my email: carlos.miguel@tecnico.ulisboa.pt, I would like to keep in touch, now through mail or another type of communication, and not expand this off-topic interest ahah

**Comment by Hopedreams** [comment]
Hi @arduinepo，I'm wondering if you've gotten the code to work to run Gaze360 with detectron2? I saw your comment at erkil1452/gaze360#5 and I'm curious about your progress.Can you release code？
