### ISSUE TITLE
Missing data for rec_079 which has samples in the test category

### ISSUE THREAD

**Issue by RSKothari** [erkil1452/gaze360#7]
`loc = (metadata['split'] == 2) & (metadata['recordings'][metadata['recording']] == 'rec_079')`
`print(np.sum(loc))`

It tells me that there are 733 images in test.

**Comment by recasens** [comment]
Hi! 

Can you try again to download the dataset? I just double checked and images for rec_79 are in the dataset package that you can download from the website.

Best wishes,

**Comment by RSKothari** [comment]
Hi thanks for getting back to me. Downloading in progress! Although the speed is quite low. I'll let you know if I have any more issues. Closing this for now.
