### ISSUE TITLE
Code for domain adaptation

### ISSUE THREAD

**Issue by zkf1997** [erkil1452/gaze360#8]
Hi, from the paper I find a part using unsupervised method for domain adaptation to unseen people, would the code for this part be available?

**Comment by recasens** [comment]
Hi, 

Thanks for asking. The code for that part of the paper is not available in the repository and we won't be able to make it available at least in the short term. We will see if we can make it public in the future, but at this point it is not available. 

Apologies and best wishes,

**Comment by XiaoLaoDi** [comment]
@zkf1997 Hi, did you find a way out ?

**Comment by XiaoLaoDi** [comment]
@recasens Some experiments with insights in https://github.com/corenel/pytorch-adda, but no improvements made in cross domain task (from RGB to IR images), would you mind to give some experimental suggestions ?
